load("//uml:plantuml_png.bzl", "plantuml_png")

plantuml_png(
    name = "ras_authorization_flow_png",
    src = "ras_authorization_flow.plantuml"
)

plantuml_png(
    name = "ras_authorization_flow_simplified_png",
    src = "ras_authorization_flow_simplified.plantuml"
)

plantuml_png(
    name = "wga_session_flow_png",
    src = "wga_session_flow.plantuml"
)

plantuml_png(
    name = "wga_session_flow_simplified_png",
    src = "wga_session_flow_simplified.plantuml"
)
